name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npx expo@54.0.33 export --platform web

      - name: Fix paths
        run: |
          sed -i 's|href="/favicon.ico"|href="/matchpoint-rn/favicon.ico"|g' dist/index.html
          sed -i 's|src="/_expo/|src="/matchpoint-rn/_expo/|g' dist/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist